<?php

declare(strict_types=1);

namespace App\Infrastructure\Processing;

enum AssetProcessingJobHandlingOutcome: string
{
    case DEAD_LETTERED = 'DEAD_LETTERED';
    case DISCARDED_INVALID_ASSET_ID = 'DISCARDED_INVALID_ASSET_ID';
    case DISCARDED_MALFORMED_PAYLOAD = 'DISCARDED_MALFORMED_PAYLOAD';
    case DISCARDED_UNKNOWN_ASSET = 'DISCARDED_UNKNOWN_ASSET';
    case PROCESSED_ASSET_FAILED = 'PROCESSED_ASSET_FAILED';
    case PROCESSED_ASSET_UPLOADED = 'PROCESSED_ASSET_UPLOADED';
    case RETRYABLE_PROCESSING_FAILURE = 'RETRYABLE_PROCESSING_FAILURE';
    case SKIPPED_ASSET_NOT_PROCESSING = 'SKIPPED_ASSET_NOT_PROCESSING';
}
